# Generated by Django 3.0.6 on 2020-05-10 06:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('intro', models.CharField(max_length=250)),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('ModDate', models.DateField(verbose_name='moddate')),
                ('status', models.CharField(max_length=20)),
                ('Comment', models.CharField(max_length=250)),
                ('PushStatus', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
