# Generated by Django 3.0.6 on 2020-05-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0003_auto_20200510_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpage',
            name='status',
            field=models.CharField(max_length=20, verbose_name='edit'),
        ),
    ]
