# Generated by Django 3.0.6 on 2020-05-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0004_auto_20200510_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpage',
            name='Comment',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='draftpage',
            name='PushStatus',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='draftpage',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
